name: Using a custom action

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: testing-githubapps/slack-reuse@main
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          pipeline-name: ${{ github.workflow }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
